name: Run the fast data morph script

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 5
    
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
     
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Create conda environment if needed
        run: |
           source $CONDA/etc/profile.d/conda.sh
           conda env create -f env_mini_v2.yml

      - name: Run script
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_mini_v2
          cd $GITHUB_WORKSPACE
          python fastdatamorph.py

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: *.png

        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

       
